# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Benjamin/Documents/Word documents/CPP/ECE 5850/5850-Ublaze-Applications/src/uBlaze_Applications/uBlaze_Applications.srcs/sources_1/bd/base_mb/ip/base_mb_xbar_0/base_mb_xbar_0.xci
# IP: The module: 'base_mb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Documents/Word documents/CPP/ECE 5850/5850-Ublaze-Applications/src/uBlaze_Applications/uBlaze_Applications.srcs/sources_1/bd/base_mb/ip/base_mb_xbar_0/base_mb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_mb_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Benjamin/Documents/Word documents/CPP/ECE 5850/5850-Ublaze-Applications/src/uBlaze_Applications/uBlaze_Applications.srcs/sources_1/bd/base_mb/ip/base_mb_xbar_0/base_mb_xbar_0.xci
# IP: The module: 'base_mb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Documents/Word documents/CPP/ECE 5850/5850-Ublaze-Applications/src/uBlaze_Applications/uBlaze_Applications.srcs/sources_1/bd/base_mb/ip/base_mb_xbar_0/base_mb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_mb_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
